# 01 - Data Cleaning
Dataset obsahuje záznamy o pacientech nemocnic - diagnózy, hospitalizace, pojištění a výsledky testů.

## Cíl
Připravit data pro EDA - odstranit duplicity, opravit datové typy a sjednotit formáty.



Healthcare Dataset
Name: This column represents the name of the patient associated with the healthcare record.

Age: The age of the patient at the time of admission, expressed in years.

Gender: Indicates the gender of the patient, either "Male" or "Female."

Blood Type: The patient's blood type, which can be one of the common blood types (e.g., "A+", "O-", etc.).
Medical Condition: This column specifies the primary medical condition or diagnosis associated with the patient, such as "Diabetes," "Hypertension," "Asthma," and more.
Date of Admission: The date on which the patient was admitted to the healthcare facility.

Doctor: The name of the doctor responsible for the patient's care during their admission.

Hospital: Identifies the healthcare facility or hospital where the patient was admitted.
Insurance Provider: This column indicates the patient's insurance provider, which can be one of several options, including "Aetna," "Blue Cross," "Cigna," "UnitedHealthcare," and "Medicare."
Billing Amount: The amount of money billed for the patient's healthcare services during their admission. This is expressed as a floating-point number.
Room Number: The room number where the patient was accommodated during their admission.
Admission Type: Specifies the type of admission, which can be "Emergency," "Elective," or "Urgent," reflecting the circumstances of the admission.

Discharge Date: The date on which the patient was discharged from the healthcare facility, based on the admission date and a random number of days within a realistic range.

Medication: Identifies a medication prescribed or administered to the patient during their admission. Examples include "Aspirin," "Ibuprofen," "Penicillin," "Paracetamol," and "Lipitor."
Test Results: Describes the results of a medical test conducted during the patient's admission. Possible values include "Normal," "Abnormal," or "Inconclusive," indicating the outcome of the test.

Analytické otázky

1. Demografické: Jaké je rozložení pacientů podle věku a pohlaví? Která věková skupina je nejčastěji hospitalizována?
2. Diagnózy: Která onemocnění jsou nejčastější? Liší se diagnózy podle pohlaví nebo věkové skupiny?
3. Finance: Jaká je průměrná výše účtu podle diagnózy / pojišťovny / typu přijetí? Která pojišťovna "platí nejvíce"?
4. Provoz nemocnice: Jak dlouho pacienti průměrně leží v nemocnici (délka hospitalizace)? Liší se to podle diagnózy nebo typu přijetí?
5. Výsledky testů: Jak se liší výsledky testů podle diagnózy nebo věku?

In [1]:
import pandas as pd

In [10]:
#1. Načtení dat
df = pd.read_csv("../data/healthcare_dataset.csv")
df.head(50)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive
10,mIchElLe daniELs,72,Male,O+,Cancer,2020-04-19,John Duncan,Schaefer-Porter,Medicare,12576.795609,394,Urgent,2020-04-22,Paracetamol,Normal
11,aaRon MARtiNeZ,38,Female,A-,Hypertension,2023-08-13,Douglas Mayo,Lyons-Blair,Medicare,7999.586880,288,Urgent,2023-09-05,Lipitor,Inconclusive
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
13,rObeRt bAuer,68,Female,AB+,Asthma,2020-05-22,Theresa Freeman,Rivera-Gutierrez,UnitedHealthcare,33207.706634,309,Urgent,2020-06-19,Lipitor,Normal
14,bROOkE brady,44,Female,AB+,Cancer,2021-10-08,Roberta Stewart,Morris-Arellano,UnitedHealthcare,40701.599227,182,Urgent,2021-10-13,Paracetamol,Normal
15,MS. nAtalIE gAMble,46,Female,AB-,Obesity,2023-01-01,Maria Dougherty,Cline-Williams,Blue Cross,12263.357425,465,Elective,2023-01-11,Aspirin,Inconclusive
16,haley perkins,63,Female,A+,Arthritis,2020-06-23,Erica Spencer,Cervantes-Wells,UnitedHealthcare,24499.847904,114,Elective,2020-07-14,Paracetamol,Normal
17,mRS. jamiE cAMPBELl,38,Male,AB-,Obesity,2020-03-08,Justin Kim,"Torres, and Harrison Jones",Cigna,17440.465444,449,Urgent,2020-04-02,Paracetamol,Abnormal
18,LuKE BuRgEss,34,Female,A-,Hypertension,2021-03-04,Justin Moore Jr.,Houston PLC,Blue Cross,18843.023018,260,Elective,2021-03-14,Aspirin,Abnormal
19,dANIEL schmIdt,63,Male,B+,Asthma,2022-11-15,Denise Galloway,Hammond Ltd,Cigna,23762.203579,465,Elective,2022-11-22,Penicillin,Normal
20,tIMOTHY burNs,67,Female,A-,Asthma,2023-06-28,Krista Smith,Jones LLC,Blue Cross,42.514589,115,Elective,2023-07-02,Aspirin,Normal
21,ChRISToPHEr BRiGhT,48,Male,B+,Asthma,2020-01-21,Gregory Smith,Williams-Davis,Aetna,17695.911622,295,Urgent,2020-02-09,Lipitor,Normal
22,KatHRYn StewArt,58,Female,O+,Arthritis,2022-05-12,Vanessa Newton,Clark-Mayo,Aetna,5998.102908,327,Urgent,2022-06-10,Lipitor,Inconclusive
23,dR. EilEEn thomPsoN,59,Male,A+,Asthma,2021-08-02,Donna Martinez MD,and Sons Smith,Aetna,25250.052428,119,Urgent,2021-08-12,Lipitor,Inconclusive
24,PAUl hEndERsOn,72,Female,AB+,Hypertension,2020-05-15,Stephanie Kramer,Wilson Group,Medicare,33211.295419,109,Emergency,2020-06-08,Paracetamol,Inconclusive
25,PeTER fiTzgeRaLd,73,Male,AB+,Obesity,2020-05-15,Angela Contreras,Garner-Bowman,Medicare,19746.832008,162,Urgent,2020-05-20,Aspirin,Abnormal
26,cathy sMaLl,51,Female,O-,Asthma,2023-12-23,Wendy Glenn,"Brown, and Jones Weaver",Blue Cross,26786.529555,401,Elective,2024-01-19,Ibuprofen,Normal
27,mr. KenNEth MoORE,34,Female,A+,Diabetes,2022-06-21,James Ellis,Serrano-Dixon,UnitedHealthcare,18834.801341,157,Emergency,2022-06-30,Lipitor,Abnormal
28,MaRy hUNter,38,Female,O-,Hypertension,2021-01-03,Jared Bruce Jr.,Gardner-Miller,Cigna,32643.299353,223,Emergency,2021-01-16,Penicillin,Normal
29,jOSHUA OLiVer,63,Female,B+,Hypertension,2023-10-03,Brandy Mitchell,Guerrero-Boone,Aetna,5767.011054,293,Elective,2023-10-12,Paracetamol,Abnormal
30,ThOMAS MartInEZ,34,Male,B-,Asthma,2019-08-18,Jacob Huynh,Hart Ltd,Cigna,47909.128810,371,Urgent,2019-09-01,Ibuprofen,Inconclusive
31,JAmES pattERson,23,Female,A+,Arthritis,2019-11-03,Kristina Frazier,Cruz-Santiago,UnitedHealthcare,25835.323595,108,Urgent,2019-11-29,Penicillin,Abnormal
32,WilLIAM cOOPEr,78,Male,AB-,Arthritis,2023-05-18,John Hartman,Group Duncan,Medicare,17993.226200,245,Elective,2023-06-15,Penicillin,Normal
33,Erin oRTEga,43,Male,AB-,Cancer,2023-05-24,Heather Garcia,Lopez-Phillips,Medicare,21185.953530,494,Elective,2023-06-03,Ibuprofen,Normal
34,NicOlE RodriGUEz,30,Female,AB+,Diabetes,2020-01-17,Lynn Young,Poole Inc,Blue Cross,8408.949354,285,Emergency,2020-02-10,Lipitor,Normal
35,DAvID AndErSON,25,Female,AB+,Asthma,2021-01-07,Emma Allison,Sons and Cox,Medicare,45453.418546,228,Elective,2021-01-26,Lipitor,Abnormal
36,DEnIse ToRRES,33,Male,AB+,Diabetes,2019-10-14,Laura Myers,LLC Martin,Aetna,4397.776995,481,Urgent,2019-10-19,Paracetamol,Inconclusive
37,CasSAndrA Robinson,26,Female,B-,Hypertension,2021-12-19,Travis Parsons,Espinoza-Stone,Aetna,9380.325968,212,Urgent,2022-01-16,Ibuprofen,Normal
38,NIcOlE LUcErO,70,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48290.693407,113,Emergency,2022-03-29,Lipitor,Abnormal
39,PAmela fErNanDeZ,57,Female,B-,Obesity,2021-01-17,Emily Taylor,Walton-Meyer,Medicare,32973.940833,272,Urgent,2021-01-29,Penicillin,Abnormal
40,chRiSTOPHer LEe,74,Female,B-,Hypertension,2021-09-15,William Reynolds,PLC Young,Cigna,49943.278499,478,Emergency,2021-10-05,Lipitor,Normal
41,ThomAS morsE,81,Male,A+,Hypertension,2020-01-27,Jennifer Carter,Meadows Group,Cigna,35633.955454,196,Urgent,2020-02-09,Aspirin,Normal
42,Mr. eRiC Lane,49,Female,A-,Asthma,2022-06-24,Matthew Thomas,"and Howell Brooks, Rogers",Cigna,25966.328610,418,Elective,2022-07-18,Paracetamol,Normal
43,KAThEriNE SmiTH,26,Female,AB+,Obesity,2021-06-09,Mary Logan,"and Mcclure White Boone,",UnitedHealthcare,21784.445071,410,Urgent,2021-07-01,Paracetamol,Normal
44,pAUL wILLiAmS,81,Female,AB-,Cancer,2020-08-23,Kristin Martinez,"Gates Brown, and Stuart",Medicare,42684.558885,328,Urgent,2020-09-08,Penicillin,Abnormal
45,lYNn MaRtinez,65,Male,O+,Cancer,2022-10-12,Daniel Murphy,Group Armstrong,Medicare,45585.886560,300,Emergency,2022-11-02,Penicillin,Normal
46,chRIsTOpHEr CHaPmAN,31,Female,O+,Hypertension,2021-12-01,Emily Patterson,Ltd Schwartz,Cigna,29615.441864,211,Elective,2021-12-09,Paracetamol,Normal
47,CHRis fRYe,58,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992.273688,413,Urgent,2020-05-13,Aspirin,Normal
48,kyLE bEnneTT,22,Male,O+,Hypertension,2023-09-09,John Smith,"Knight and Nguyen, Riggs",UnitedHealthcare,28051.499484,157,Urgent,2023-09-23,Ibuprofen,Abnormal
49,BRandOn coLLINS,77,Female,O+,Asthma,2019-07-19,Cameron Young,Lopez PLC,Cigna,16320.232447,138,Urgent,2019-07-29,Ibuprofen,Abnormal

In [3]:
#2. Prozkoumání struktury
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [1]:
#3. Odstranění duplicit
df.duplicated().sum()
df = df.drop_duplicates()

NameError: name 'df' is not defined

In [5]:
#3.1. Kontrola odstranění duplicit
df.duplicated().sum()

np.int64(0)

In [6]:
#4. Předevední textu na datum
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  object
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  object
 3   Blood Type          54966 non-null  object
 4   Medical Condition   54966 non-null  object
 5   Date of Admission   54966 non-null  datetime64[ns]
 6   Doctor              54966 non-null  object
 7   Hospital            54966 non-null  object
 8   Insurance Provider  54966 non-null  object
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  object
 12  Discharge Date      54966 non-null  datetime64[ns]
 13  Medication          54966 non-null  object
 14  Test Results        54966 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.7+ MB

In [ ]:
#5. Sjednocení jmen
df["Name"]= df["Name"].str.title()
df.head(100)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Catherine Gardner,79,Female,A-,Hypertension,2019-08-19,David Ruiz,James Ltd,Medicare,25503.673807,144,Elective,2019-08-26,Lipitor,Abnormal
96,Anne Thompson,76,Female,O+,Diabetes,2024-03-24,Kyle Smith,Kemp-Munoz,Aetna,6312.607691,226,Elective,2024-04-14,Aspirin,Abnormal
97,Todd Cooper,55,Female,A+,Diabetes,2022-12-10,Jason Price,Henderson-Taylor,UnitedHealthcare,21772.341399,459,Elective,2022-12-31,Ibuprofen,Normal
98,Phillip Lyons,53,Male,B-,Cancer,2022-09-14,Stephanie Clements,"Parsons, Hartman Martinez and",Blue Cross,30437.001788,208,Elective,2022-09-18,Aspirin,Normal
99,Mark Ford,18,Male,B+,Asthma,2022-10-18,Steven James,Luna Inc,UnitedHealthcare,28837.677053,227,Elective,2022-11-11,Aspirin,Abnormal

In [30]:
#6. Sjednocení unikátních hodnot
for column in ["Gender", "Blood Type", "Hospital", "Insurance Provider",  "Admission Type",  "Medication",  "Test Results"]:
    df [column].unique()
    print(df [column].unique())

['Male' 'Female']
['B-' 'A+' 'A-' 'O+' 'AB+' 'AB-' 'B+' 'O-']
['Sons and Miller' 'Kim Inc' 'Cook PLC' ... 'Guzman Jones and Graves,'
 'and Williams, Brown Mckenzie' 'Moreno Murphy, Griffith and']
['Blue Cross' 'Medicare' 'Aetna' 'UnitedHealthcare' 'Cigna']
['Urgent' 'Emergency' 'Elective']
['Paracetamol' 'Ibuprofen' 'Aspirin' 'Penicillin' 'Lipitor']
['Normal' 'Inconclusive' 'Abnormal']

In [ ]:
#6. Uložení souboru
df.to_csv("../data/healthcare_dataset_cleaned.csv", index=False)

NameError: name 'df' is not defined